---
services:
  traefik:
    image: traefik:v3.1.5
    restart: always
    ports:
      - "81:80"       # HTTP traffic (redirects to HTTPS)
      - "443:443"     # HTTPS traffic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config
      - ./traefik/acme:/etc/traefik/acme
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    networks:
      - traefik-with-n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`yourdoamin.com`) && PathPrefix(`/`)" 
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.middlewares=n8n-headers"
      - "traefik.http.middlewares.n8n-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.n8n-headers.headers.accesscontrolalloworigin=*"
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_PASSWORD=Your_Password
      - POSTGRES_USER=n8n
    networks:
      - traefik-with-n8n
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=Your_Password
      - N8N_HOST=yourdomain.com
      - N8N_PORT=5678
      - WEBHOOK_URL=https://yourdomain.com
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # Security recommendations (uncomment and customize)
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=your-strong-password
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - traefik-with-n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      # Security middleware (recommended)
      - "traefik.http.routers.n8n.middlewares=security-headers@file"
      # Uncomment for basic auth at Traefik level
      # - "traefik.http.routers.n8n.middlewares=auth-n8n"
      # - "traefik.http.middlewares.auth-n8n.basicauth.users=admin:$$apr1$$9Cv/OMGj$$ZomWQzuQbL.3TRCS81A1g/"

volumes:
  postgres-data:
  n8n-data:

networks:
  traefik-with-n8n:
    external: true
